title: Backup Parachute Software
description: A portfolio of software built to last by a SaaS operator with 27 years of experience. Products, tools, and articles from the Backup Parachute team.
url: https://backupparachute.com
author: Kyle Miller
linkedin: https://www.linkedin.com/company/backup-parachute-software
github: https://github.com/backupparachute/
email: info@backupparachute.com
phone: 888-865-2012

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-seo-tag

collections:
  products:
    output: true
    permalink: /products/:path/

defaults:
  - scope:
      path: ""
      type: products
    values:
      layout: product
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
  - scope:
      path: "libs/**"
    values:
      sitemap: false

permalink: /articles/:title/

exclude:
  - bower.json
  - README.md
  - node_modules
  - gulpfile.js
  - package.json
  - package-lock.json
  - raw_assets
  - Gemfile
  - Gemfile.lock
  - vendor

sass:
  style: compressed
  sass_dir: _sass
