title: Backup Parachute Software
description: We leverage open source software to craft solutions that empower our clients to reach the next level.
url: https://backupparachute.com
twitter: https://twitter.com/backupparachute
linkedin: https://www.linkedin.com/company/backup-parachute-software
github: https://github.com/backupparachute/
email: info@backupparachute.com
phone: 888-865-2012

plugins:
  - jekyll-sitemap

# Outputting
permalink: pretty

exclude:
- bower.json
- README.md
- node_modules
- gulpfile.js
- package.json
- raw_assets

sass:
  style: compressed
  sass_dir: /

defaults:
  -
    scope:
      path:            "libs/**"
    values:
      sitemap:         false