title: Backup Parachute Software
description: We leverage open source software to craft solutions that empower our clients to reach the next level.

gems:
  - jekyll-sitemap

# Outputting
permalink: pretty

exclude:
- bower.json
- README.md
- node_modules
- gulpfile.js
- package.json
- raw_assets

sass:
  style: compressed
  sass_dir: /
